# Generated by Django 2.2.3 on 2021-10-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'verbose_name': 'Content category', 'verbose_name_plural': 'Content categories'},
        ),
    ]
