# Generated by Django 2.2.3 on 2021-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20211029_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='long_text',
            new_name='long_text_ar',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='short_text',
            new_name='short_text_ar',
        ),
        migrations.AddField(
            model_name='content',
            name='long_text_du',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='long_text_en',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='long_text_fa',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='short_text_du',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='short_text_en',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='short_text_fa',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
