# Generated by Django 2.2.3 on 2020-05-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='room/floors')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('front_image', models.ImageField(upload_to='room/walls')),
                ('left_image', models.ImageField(upload_to='room/walls')),
                ('right_image', models.ImageField(upload_to='room/walls')),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='room/decorations')),
                ('position_left', models.CharField(blank=True, max_length=10, null=True)),
                ('position_right', models.CharField(blank=True, max_length=10, null=True)),
                ('position_top', models.CharField(blank=True, max_length=10, null=True)),
                ('position_bottom', models.CharField(blank=True, max_length=10, null=True)),
                ('decoration_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decorations', to='room.DecorationType')),
            ],
        ),
    ]
