# Generated by Django 2.2.3 on 2020-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room/roofs')),
                ('color_code', models.CharField(max_length=60)),
            ],
        ),
    ]
