# Generated by Django 2.2.3 on 2020-05-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roof'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roof',
            new_name='Ceiling',
        ),
    ]
