# Generated by Django 2.2.3 on 2020-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20200523_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceiling',
            name='color_code',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
