"""
Django settings for ghalichin project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a&0+@j*)e+jbttarm7)k&@1%fb+1onh=f%-bw!*2hntew+3%$^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '50.6.249.173',
    'localhost',
    '127.0.0.1',
    'api.daralfarsha.com',
    'https://api.daralfarsha.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'knox',
    'cities',
    'colors',
    'manufacturers',
    'rugs',
    'sellers',
    'blog',
    'room',
    'landing',
    # 'django_extensions',
    'user_profile',
    'accounts',
    'drf_yasg',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#FORCE_SCRIPT_NAME = '/api'
ROOT_URLCONF = 'ghalichin.urls'

# ??? ?? ????? ????? ?? ??? ???? ????? ??????
#LOGIN_REDIRECT_URL = '/api/'
#LOGIN_URL = '/api/admin/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ghalichin.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',      #_psycopg2
        'NAME': 'darolfarsh',
        'USER': 'darolfarsh',
        'PASSWORD': 'babak_keyvan_',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c TimeZone=UTC',
        },
        'CONN_MAX_AGE': 0,
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False       #taghir

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/s/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
#     # '/var/www/static/',
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, "assets")

# MEDIA_URL = "/files/"
MEDIA_URL = "/m/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
        #'rest_framework.authentication.SessionAuthentication'
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://daralfarsha.com",
    "daralfarsha.com",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# CORS_ORIGIN_WHITELIST = [
#     "https://daralfarsha.com",
#     "http://localhost:3000",
# ]


# Password reset token expiry (Django 2.2)
PASSWORD_RESET_TIMEOUT_DAYS = 1 /96  # 15 minutes

#forgot password part
FRONTEND_BASE_URL = "https://daralfarsha.com"#in ro bayad taghir bedim vaghti raftim roo server va url dorost
                                            #ro benevisim masalan intori : FRONTEND_BASE_URL = "https://your-frontend-domain.com"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"    # berim roo server in ro comment kon
DEFAULT_FROM_EMAIL = "Darolfarsh <noreply@localhost>"
# Email (SMTP)
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "mail.yourdomain.com"          # یا smtp.yourdomain.com (از هاست بگیر)
# EMAIL_PORT = 465    # For SSL , if we use TLS Email_Port must be 587
# EMAIL_HOST_USER = "noreply@yourdomain.com"
# EMAIL_HOST_PASSWORD = "YOUR_EMAIL_PASSWORD"
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True
