# Generated by Django 2.2.3 on 2020-02-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rugs', '0001_initial'),
        ('cities', '0001_initial'),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('address', models.CharField(blank=True, max_length=360, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=360, null=True)),
                ('map_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers')),
                ('brands', models.ManyToManyField(blank=True, related_name='brands', to='manufacturers.Manufacturer')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City')),
                ('representations', models.ManyToManyField(blank=True, related_name='representations', to='manufacturers.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SellerRug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('available_sizes', models.IntegerField(default=1)),
                ('rug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugs.Rug')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='rugs',
            field=models.ManyToManyField(through='sellers.SellerRug', to='rugs.Rug'),
        ),
    ]
