# Generated by Django 2.2.3 on 2020-12-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrug',
            name='buy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
