# Generated by Django 2.2.3 on 2021-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerrug_buy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='vr_file',
            field=models.FileField(blank=True, null=True, upload_to='vr_files'),
        ),
    ]
