# Generated by Django 2.2.3 on 2020-02-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('color_code', models.CharField(blank=True, max_length=160, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=160, null=True)),
                ('decimal_code', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
    ]
