# Generated by Django 2.2.3 on 2020-02-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
