# Generated by Django 2.2.3 on 2020-02-05 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RugBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='backgrounds')),
            ],
        ),
        migrations.CreateModel(
            name='RugBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='borders')),
            ],
        ),
        migrations.CreateModel(
            name='RugCorner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='corners')),
            ],
        ),
        migrations.CreateModel(
            name='RugPartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RugTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='tiles')),
            ],
        ),
        migrations.CreateModel(
            name='RugToranj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='toranjs')),
            ],
        ),
        migrations.CreateModel(
            name='RugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YarnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=260, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugBackground')),
                ('border', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugBorder')),
                ('corner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugCorner')),
                ('rug_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rugs.RugType')),
                ('tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugTile')),
                ('toranj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugToranj')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RugPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='parts')),
                ('density', models.IntegerField(blank=True, null=True)),
                ('shaneh', models.IntegerField(blank=True, null=True)),
                ('coloring_code', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturers.Manufacturer')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colors.Color')),
                ('colors', models.ManyToManyField(blank=True, related_name='parts_colors', to='colors.Color')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rugs.RugPartType')),
                ('rug_types', models.ManyToManyField(blank=True, to='rugs.RugType')),
                ('yarn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rugs.YarnType')),
            ],
        ),
        migrations.CreateModel(
            name='RugLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugBackground')),
                ('border', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugBorder')),
                ('corner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugCorner')),
                ('rug_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rugs.RugType')),
                ('tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugTile')),
                ('toranj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugToranj')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rugbackground',
            name='rug_types',
            field=models.ManyToManyField(blank=True, to='rugs.RugType'),
        ),
        migrations.CreateModel(
            name='Rug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('w_density', models.IntegerField(blank=True, null=True)),
                ('l_density', models.IntegerField(blank=True, null=True)),
                ('coloring_code', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_image', models.ImageField(blank=True, null=True, upload_to='rugs')),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugBackground')),
                ('background_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_rugs', to='rugs.RugPart')),
                ('border', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugBorder')),
                ('border_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='border_rugs', to='rugs.RugPart')),
                ('colors', models.ManyToManyField(blank=True, to='colors.Color')),
                ('corner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugCorner')),
                ('corner_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corner_rugs', to='rugs.RugPart')),
                ('knot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rugs.KnotType')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturers.Manufacturer')),
                ('rug_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rugs.RugType')),
                ('tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugTile')),
                ('tile_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tile_rugs', to='rugs.RugPart')),
                ('toranj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rugs.RugToranj')),
                ('toranj_n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='toranj_rugs', to='rugs.RugPart')),
                ('yarn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rugs.YarnType')),
            ],
        ),
    ]
