# Generated by Django 2.2.3 on 2020-02-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruglog',
            name='parts',
            field=models.ManyToManyField(blank=True, to='rugs.RugPart'),
        ),
    ]
