# Generated by Django 2.2.3 on 2020-02-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0002_ruglog_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rugpart',
            name='rug_types',
        ),
    ]
