# Generated by Django 2.2.3 on 2020-02-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0003_remove_rugpart_rug_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rug',
            name='background',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='border',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='corner',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='tile',
        ),
        migrations.RemoveField(
            model_name='rug',
            name='toranj',
        ),
        migrations.AddField(
            model_name='rug',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pattern_rugs', to='rugs.RugPart'),
        ),
    ]
