# Generated by Django 2.2.3 on 2020-02-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0004_auto_20200216_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rug',
            old_name='background_n',
            new_name='background',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='border_n',
            new_name='border',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='corner_n',
            new_name='corner',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='tile_n',
            new_name='tile',
        ),
        migrations.RenameField(
            model_name='rug',
            old_name='toranj_n',
            new_name='toranj',
        ),
    ]
