# Generated by Django 2.2.3 on 2020-08-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0005_auto_20200216_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='rug',
            name='rug_sizes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
