# Generated by Django 2.2.3 on 2021-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0006_rug_rug_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RugReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('rug_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='rug_replacements')),
            ],
        ),
    ]
