# Generated by Django 2.2.3 on 2021-10-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0007_rugreplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRugSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rugreplacement',
            options={'verbose_name': '------ Rug replacement request', 'verbose_name_plural': '------ Rug replacement requests'},
        ),
        migrations.CreateModel(
            name='CustomRugRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='custom_rugs')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rugs.CustomRugSize')),
            ],
            options={
                'verbose_name': '------ Custom rug request',
                'verbose_name_plural': '------ Custom rug requests',
            },
        ),
    ]
