# Generated by Django 2.2.3 on 2021-11-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0008_auto_20211029_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rugpart',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rug_parts', to='manufacturers.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='rugpart',
            name='yarn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rug_parts', to='rugs.YarnType'),
        ),
    ]
